### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by hackruu** [tyjtyj/python-broadlink-livolo#1]
i'm struggling to get this to work. I even tried patch from your branch "patch-1" but no success still. broadlink sending some data(orange led is on), but no success.
where does '6500' number came from? maybe you can push your patches to upstream module?
thanks.

**Comment by tyjtyj** [comment]
Did u get ur remote id? If u dont u need to teach ur livolo the remote first

6500 is just example. It can be any number and nobody know which number works.. For sure 6500 works.

**Comment by hackruu** [comment]
thanks for an answer. how should i get the id?

**Comment by tyjtyj** [comment]
There is few way which involve connecting rf receiver or tear apart your remote. See discussion here 
https://forum.arduino.cc/index.php?topic=153525.0

I dont see a point getting remote ID, simply guess and it take lots less effort and Livolo switch can learn more that 10 id.

**Comment by hackruu** [comment]
i actually found your https://www.tyjtyj.com/livolo.php and it seems like it's working fine with https://github.com/lprhodes/homebridge-broadlink-rm. thank you. can you opensource your php script?

**Comment by tyjtyj** [comment]
its a dummy java script. right click and view source :)

**Comment by hackruu** [comment]
thanks.
after playing some time with scene codes i generated my switches start to double press sometime, turning on and immediate off. what i probably done wrong? i see double led blinking broadlink when it's happenning... i'm sending the same code, sometimes it's sent with one led blink, sometimes with double.

**Comment by tyjtyj** [comment]
do u use my code or home-bridge ? 
i been using this code for months and never double press. 

If it is still issue with double press, maybe can try use on only code and off only code.. double press wont do any harm

**Comment by hackruu** [comment]
i cannot get your python-broadlink-livolo to work.
however i'm using python-broadlink's cli right now for testing purposes and having issues with double press. i generate hex codes with your javascript.

**Comment by tyjtyj** [comment]
probably u get better support from python-broadlink cli page on the double press issue. 

my https://www.tyjtyj.com/livolo.php just create RF code and does not cause the double press.

**Comment by hackruu** [comment]
when i input different RemoteID and press generate on https://www.tyjtyj.com/livolo.php i get different output hex length. Does hex length indicates if i'm choosing incorrect RemoteID? 
can i use your js page to reverse hex to get my own remotes RemoteID so i don't have to open their case?

thanks.

**Comment by tyjtyj** [comment]
in fact is remoteID is reversible but I dont have time to write code for it . 

0c means 1
0606 mean 0
remove the header b280260013 and remove last 7 of 0c/0606 will give you the remoteid in binary.
Convert to dec, will get your remoteid number. 


basically it is b280260013 + remoteid + btn

hex length does not matter. 

PS: I updated the page with some instructions

**Comment by hackruu** [comment]
> PS: I updated the page with some instructions

i don't see any significant changes in last commit.

> probably u get better support from python-broadlink cli page on the double press issue.

thanks for a hint!
actually i found the issue. it is python-broadlink library itself, when i downgrade pip library to 0.3 i started getting 
```
Traceback (most recent call last):
  File "/root/python-broadlink/cli/broadlink_cli", line 114, in <module>
    dev.send_data(data)
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 450, in send_data
    self.send_packet(0x6a, packet)
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 250, in send_packet
    response = self.cs.recvfrom(1024)
socket.timeout: timed out
```
errors which prevents from happening double presses. very sad, but it's okay as workaround.

> basically it is b280260013 + remoteid + btn

here's list of my previously sniffed packets with two new generated with your script. 
```
bedroomon = e973260013060606060606060606060606060606060b0c0b0b06060b0b0b0c060606060c0606060606060000
bedroomoff = e973260013060606060606060606060606060606060b0c0b0b06060b0b0b0c060606060c0606060606060000
zalon = e96f260013060606060606060606060606060606060c0b0b0b06060c0b0b0c06060b06060606060606060000
koridoron = e973260013060606060606060606060606060606060b0c0b0c06060c0b0b06060b06060c0606060606060000
sorton = b2802600130606060606060c0c0c060606060c0c0c06060c06060606060606060c06060c0606060606060000
vannaon = b2802600130606060606060c0c060606060c0606060606060606060606060606060606060c06060c0606060606060000000000000000000000000000
```

as you can see, my previous codes are not starting from "b280". why is it so?

**Comment by tyjtyj** [comment]
I gonna just ignore the header different assuming it just a data inconsistency during learning. 

From your bedroom i got code 

e973260013 = header

060606060606060606060606060606060b0c0b0b06060b0b0b0c060606060c060606060606 + 0000

ignore the last 0000 as they are padding.
replace 0606 with 0
and 0b/0c with 1 

u get as below with split last 7 bit 
0000000011110111 1001000  + 0000

0000000011110111 give your remote id 247 
1001000 = 72 which is  btn9

This is first time i seeing remote id none divisible by 4

I update https://www.tyjtyj.com/livolo.php on how to use the generator

**Comment by hackruu** [comment]
very nice update, thanks.
i used it to let all my livolo switches to learn 6550 scene. all livolo switches now react to it and set their state to ON. But when i use 6550 off generated code only one switch switches off. what is wrong?
one switch that worked is 1 gang with sync line. others are two gang and 1gang+dimmer.

**Comment by tyjtyj** [comment]
Scene is for on only.
Off is based on toggle remote id.

**Comment by hackruu** [comment]
got it, thanks! wasn't intuitive at all :)

**Comment by tyjtyj** [comment]
If it works for you. I gonna close this issue. 

By the way, this code no longer maintained. 
I am replacing my livolo soon.

**Comment by hackruu** [comment]
Thank you for all your help.

**Comment by tyjtyj** [comment]
@hackruu , someone updated me on the scene function and i updated the page for off only button. 
I think u might want to know about it

**Comment by hackruu** [comment]
i will diff my copy of your page with new one to find changes, thanks
